name: ğŸš€ Auto Archive Project Done Columns
on:
  schedule:
    - cron: '* * * * *'  # æ¯å‘¨æ—¥è‡ªåŠ¨è¿è¡Œ
    

jobs:
  add-archive-project-done-columns:
    runs-on: ubuntu-latest
    steps:
      - name: archive resolved issues
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: test
          column: Resolved Issues
          repo-token: ${{ secrets.GH_PROJECT_TOKEN }}
          action: archive

      - name: archive resolved pr
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: test
          column: Resolved PR
          repo-token: ${{ secrets.GH_PROJECT_TOKEN }}
          action: archive
 

      - name: archive rejected pr
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: test
          column: Rejected PR
          repo-token: ${{ secrets.GH_PROJECT_TOKEN }}
          action: archive
 
